name: Aesthetic Dentistry of Manhattan
favicon: null
layout_spectrum: 0
typography_spectrum: 0.76702
title: 'Comprehensive Dentistry, Dental Implants, Cosmetic Dentistry'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4a4849'
    - '#0090b3'
    - '#8e8c8d'
    - '#67bdd2'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
